version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
