serverAddr = "119.45.6.168"
serverPort = 55363
auth.method = "token"
auth.token = "77K80wS00T1E"

[[proxies]]
name = "rdp"
type = "tcp"
localIP = "172.17.0.1"
localPort = 3389
remotePort = 3389

[[proxies]]
name = "smb"
type = "tcp"
localIP = "172.17.0.1"
localPort = 445
remotePort = 445

[[proxies]]
name = "nextcloud"
type = "tcp"
localIP = "172.18.0.2"
localPort = 80
remotePort = 80

[[proxies]]
name = "photoprism"
type = "tcp"
localIP = "172.21.0.2"
localPort = 2342
remotePort = 2342